definitions:
  controllers.Response:
    properties:
      code:
        type: integer
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  dto.MiniLinkStatus:
    properties:
      status:
        type: string
    type: object
  dto.ResRegister:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dto.User'
    type: object
  dto.ResToken:
    properties:
      token:
        type: string
    type: object
  dto.User:
    properties:
      email:
        type: string
      openId:
        type: string
      phone:
        type: string
      user_id:
        type: string
      username:
        type: string
      wechat_nickname:
        type: string
    type: object
  dto.UserLoginByEmail:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.UserLoginByPhone:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  dto.UserRegisterByEmail:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    type: object
  dto.UserRegisterByPhone:
    properties:
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    required:
    - password
    - phone
    type: object
info:
  contact:
    email: support@fit2cloud.com
    name: Fit2cloud Support
    url: https://www.fit2cloud.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kubeoperator.io
  title: KubeOperator Restful API
  version: "1.0"
paths:
  /auth/loginByEmail:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginByEmail'
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息和 token
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ResToken'
              type: object
      summary: 通过邮箱登录
      tags:
      - auth
  /auth/loginByPhone:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginByPhone'
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息和 token
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ResRegister'
              type: object
      summary: 通过手机登录
      tags:
      - auth
  /auth/registerByEmail:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterByEmail'
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息和 token
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ResRegister'
              type: object
      summary: 通过邮箱账号注册
      tags:
      - auth
  /auth/registerByPhone:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterByPhone'
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息和 token
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ResRegister'
              type: object
      summary: 通过手机注册
      tags:
      - auth
  /auth/wx/getMiniLinkStatus:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 小程序链接
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.MiniLinkStatus'
              type: object
      summary: web 端轮询当前登录链接状态
      tags:
      - auth
  /auth/wx/getOpenId:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.User'
              type: object
      summary: 获取 openId
      tags:
      - auth
  /user/getMyInfo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.User'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取自己的用户信息
      tags:
      - user
  /user/getUserByUserId:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户 userId
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.User'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
